# Generated by Django 2.1.15 on 2020-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_courseassignments_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_id', 'course')},
        ),
    ]
