# Generated by Django 2.1.15 on 2020-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20201019_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_upload',
            field=models.BooleanField(default=True),
        ),
    ]
