# Generated by Django 2.1.15 on 2020-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_assignment_last_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
