# Generated by Django 2.1.15 on 2020-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_assignment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignments',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
