# Generated by Django 2.1.15 on 2020-11-16 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20201116_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignments',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
