# Generated by Django 2.1.15 on 2020-12-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_courseassignments_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignments',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
