# Generated by Django 2.1.15 on 2021-03-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20210330_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upload.StudentsGroup'),
        ),
    ]
